-- MySQL Script generated by MySQL Workbench
-- Tue Feb 16 10:08:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_ProjetoIntegrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_ProjetoIntegrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_ProjetoIntegrador` DEFAULT CHARACTER SET utf8 ;
USE `db_ProjetoIntegrador` ;

-- -----------------------------------------------------
-- Table `db_ProjetoIntegrador`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ProjetoIntegrador`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome_categoria` ENUM("Acessórios", "Decoração", "Autocuidado", "Moda", "Beleza", "Papelaria") NOT NULL,
  `tipo_composicao` VARCHAR(45) NOT NULL,
  `tipo_publico` ENUM("Masculino", "Feminino", "Infantil", "Geral") NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ProjetoIntegrador`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ProjetoIntegrador`.`tb_usuario` (
  `idtb_usuario` INT NOT NULL,
  `nomeCompleto_usuario` VARCHAR(45) NOT NULL,
  `email_usuario` VARCHAR(45) NOT NULL,
  `senha_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ProjetoIntegrador`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ProjetoIntegrador`.`tb_produto` (
  `idtb_produto` INT NOT NULL,
  `tb_categoria_idtb_categoria` INT NOT NULL,
  `tb_usuario_idtb_usuario` INT NOT NULL,
  `nome_produto` VARCHAR(45) NOT NULL,
  `preco_produto` DOUBLE NOT NULL,
  `tamanho_produto` VARCHAR(45) NOT NULL DEFAULT 'Único',
  `foto_produto` BLOB NOT NULL,
  PRIMARY KEY (`idtb_produto`, `tb_categoria_idtb_categoria`, `tb_usuario_idtb_usuario`),
  INDEX `fk_tb_produto_tb_categoria_idx` (`tb_categoria_idtb_categoria` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_usuario1_idx` (`tb_usuario_idtb_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`tb_categoria_idtb_categoria`)
    REFERENCES `db_ProjetoIntegrador`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_usuario1`
    FOREIGN KEY (`tb_usuario_idtb_usuario`)
    REFERENCES `db_ProjetoIntegrador`.`tb_usuario` (`idtb_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
